title: Yay learnding
author: SamGrantham
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  gitlabs learning is fun
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
